config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'plans', to: 'pages#plans', as: :plans
  get 'history', to: 'pages#history', as: :history

  resources :gardens, only: %i[create index show edit update destroy] do
    resources :beds, only: %i[new create show edit update]
  end

  resources :beds, only: %i[ destroy] do
    resources :crops, only: %i[create]
  end
  resources :crops, only: %i[update destroy] do
    member do
      get :plant
      get :harvest
    end
  end

  resources :veggies, only: %i[create index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 talkbubble" role="alert">
    <%= image_tag "notice_worm.png", class: "worm-helper" %>
      <div style="height: 50px;" class="textarea d-flex justify-content-between align-items-center">
      <p style="<%= "font-size:0.7rem;" if notice.length > 48  %>">
        <%= notice %>
      </p>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon mb-1
" style="paddig-bottom: none;">
  <div class="container-fluid"
      data-controller="weather"
      data-weather-api-key-value="<%= ENV['WEATHERMAP_API_KEY'] %>">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Roots-psycho.png", class: "mb-1", style: "height: 40px; width: 119px;" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div class="dropdown" style="height: 85px">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle cloud"
                      style = "padding: none;"
                      id="navbarDropdown1"
                      href="#"
                      type="button"
                      data-bs-toggle="dropdown"
                      aria-haspopup="true"
                      aria-expanded="false">
                <div style="margin-top: 24px;">My Gardens</div>
              </a>

              <div class="dropdown-menu rounded-4 shadow border-0" aria-labelledby="navbarDropdown1">
                <%= link_to current_user.gardens.length == 1 ? "Garden Overview" : "Gardens Overview", gardens_path, class: "dropdown-item" %>
                <hr class="dropdown-divider">
                <% current_user.gardens.each do |garden| %>
                  <%= link_to garden.name, garden_path(garden), class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
          </div>
          <li class="nav-item cloud">
            <%= link_to "Plans", plans_path, class: "nav-link" %>
          </li>
          <li class="nav-item cloud">
            <%= link_to "History", history_path, class: "nav-link" %>
          </li>
          <div class="m-2">
            <li data-weather-target="icon" class="nav-item dropdown sun">
              <%= image_tag "root-st.png", class: "avatar dropdown-toggle ml-2",style: "height:42px",
                  id: "navbarDropdown2", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu rounded-4 dropdown-menu-end shadow border-0" aria-labelledby="navbarDropdown2">
                <%= link_to "Weather Forecast", "http://www.bom.gov.au/vic/forecasts/melbourne.shtml", class: "dropdown-item" %>
                <%= link_to "Gardening News", "https://www.abc.net.au/gardening", class: "dropdown-item" %>
                <%= link_to "Vegetable Info", "https://en.wikipedia.org/wiki/Vegetable", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          </div>
          <div class="m-2">
            <li class="nav-item" style="min-width: 45px;">
              <div data-weather-target="temp" class="d-flex justfy-content-start">
              </div>
            </li>
          </div>
        <% else %>
          <li class="nav-item cloud">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_page_info.html.erb
<div class="page-info w-100 ms-0">
  <div class="card rounded-4">
    <a data-bs-toggle="collapse" href="#collapseBody" aria-expanded="<%= empty %>">
      <div class="card-header w-100">
        <div class="d-flex justify-content-start align-items-center">
          <div>
            <i class="fa-solid fa-chevron-down"></i>
          </div>
          <div>
            <p class="my-0 mx-3"><strong><%= @info[:title] %> - Helpful Hints</strong></p>
          </div>
        </div>
      </div>
    </a>
    <% collapse = empty ? "collapse.show collapse show" : "collapse.show collapse" %>
    <div class="<%= collapse %>" id="collapseBody">
      <div class="card-body px-3">
        <div class="card-text rounded-4 m-3 py-3 px-5">
          <div class="brief py-2">
            <p><%= @info[:brief] %></p>
          </div>
          <div class="tip-list">
            <ul>
              <% @info[:tips].each do |tip| %>
                <li><p>🐝 <%= tip %></p></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>