config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'plans', to: 'pages#plans', as: :plans
  get 'history', to: 'pages#history', as: :history

  resources :gardens, only: %i[create index show edit update destroy] do
    resources :beds, only: %i[new create show edit update]
  end

  resources :beds, only: %i[ destroy] do
    resources :crops, only: %i[create]
  end
  resources :crops, only: %i[update destroy] do
    member do
      get :plant
      get :harvest
    end
  end

  resources :veggies, only: %i[create index]
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :beds, dependent: :destroy

  validates :name, presence: true
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[show edit update destroy]

  def index
    @gardens = current_user.gardens
    @garden = Garden.new
    @info = INDEX_INFO
  end

  def show
    @bed = Bed.new
    @beds = @garden.beds
    @crop = Crop.new
    @veggie = Veggie.new
    @season = season
    @veggie_lists_by_season = seasonal_veggie_lists
    @seasonal_titles = SEASONAL_TITLES
    @info = SHOW_INFO
  end

  def create
    @user = current_user
    @garden = Garden.new(garden_params)
    @garden.user = @user

    if @garden.save
      redirect_to gardens_path, notice: "🪴 #{@garden.name} was added!"
    else
      render partial: "gardens/new_garden_form", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @garden.update(garden_params)
      redirect_to gardens_path, notice: "🪴 #{@garden.name} was updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    garden_name = @garden.name
    if @garden.destroy
      redirect_to gardens_path, status: :see_other, notice: "🪴 #{garden_name} was removed!"
    else
      # render a _garden partial
      # render @garden, status: :unprocessable_entity
    end
  end

  def upcoming
  end

  private

  def garden_params
    params.require(:garden).permit(:name)
  end

  def set_garden
    @garden = Garden.find(params[:id])
  end

  def season
    year_day = Date.today.yday().to_i
    year = Date.today.year.to_i
    is_leap_year = ((year % 4).zero? && (year % 100 != 0)) || (year % 400).zero?
    if is_leap_year && year_day > 60
      # if is leap year  and date > 28 february
      year_day -= 1
    end

    if year_day >= 355 || year_day < 81
      result = "Summer"
    elsif year_day >= 81 && year_day < 173
      result = "Autumn"
    elsif year_day >= 173 && year_day < 266
      result = "Winter"
    elsif year_day >= 266 && year_day < 355
      result = "Spring"
    end

    result
  end

  def seasonal_veggie_lists
    seasons = %w[Summer Autumn Winter Spring]
    seasons.map { |season| Veggie.seasonal_veggies(season) }
  end

  SEASONAL_TITLES = {
    Summer: "🌻 Summer 🌻",
    Autumn: "🍁 Autumn 🍁",
    Winter: "❄️ Winter ❄️",
    Spring: "🌸 Spring 🌸"
  }

  INDEX_INFO = {
    title: "My Gardens",
    brief: "This is the gardens page, where you will find a summary of your current gardens.",
    tips: [
      "To add a new garden, click the 'Add Garden' button in the top right",
      "Buttons to edit and delete gardens can be found to the right of the garden name",
      "To view the garden simply click the garden title",
      "Crops will appear in your beds once planted, with a progress indicator to let you know when to harvest"
    ]
  }

  SHOW_INFO = {
    title: "Garden Beds",
    brief: "This is the garden page, where you will find info about beds in this garden.",
    tips: [
      "To add a new garden bed, click the 'Add bed' button in the top right",
      "To add a crop of Veggies to your garden bed, click the 'Add Crop' button in the top right corner of the bed card",
      "When adding a new crop, select the season for relavant recommendations",
      "You can plan for future crops by selecting 'No' when prompted by 'Has the crop been planted?'"
    ]
  }
end

app/views/gardens/_bed.html.erb
<% require_relative '../../../db/crop_emojis' %>

<div class="card my-4">
  <div class="card-header">
    <div class="d-flex justify-content-between">
      <div>
        <h2><%= bed.description %></h2>
      </div>

      <!-- ------------------------------- Edit BED modal1 -------------------------------- -->
      <div class="modal fade" id="editbedmodal<%= bed.id %>" aria-hidden="true" aria-labelledby="editbedmodal<%= bed.id %>" tabindex="-1">
        <div class="modal-dialog modal-lg modal-dialog-centered">
          <div class="modal-content rounded-4">
            <div class="modal-header">
              <h2 class="modal-title fs-5">Edit Bed</h2>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div class="container-fluid">
                <div class="row">
                  <%= render "beds/form", bed: bed %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <%# Menu button %>
      <div class="btn-group dropdown">
        <button type="button" class="btn btn-light" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-bars" style="font-size: 22px;"></i>
        </button>
        <ul class="dropdown-menu rounded-4 border-0 shadow" style="min-width: 130px;">

          <%# ------------- Edit Bed Button ------------- %>
          <li>
            <a class="btn btn-light" data-bs-toggle="modal" href="#editbedmodal<%= bed.id %>" role="button"><i class="fa-solid fa-pencil"></i> Edit Bed</a>
            <%# <%= link_to ('<i class="fa-solid fa-pencil"></i> Edit Bed').html_safe, edit_bed_path(bed), class:"btn btn-light" %>
          </li>

          <%# ------------- Delete Bed Button ------------- %>
          <li>
            <%= link_to ('<i class="fa-solid fa-trash-can"></i> Delete Bed').html_safe,
                bed,
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "btn btn-light"
              %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="card-body bed-card">

    <%# ------------- Add Crop Button ------------------ %>
    <div class="d-flex justify-content-end">
      <a class="btn btn-info m-2 <%= "btn-pulse-primary" if bed.planted_crops.empty? && bed.future_crops.empty? %>" data-bs-toggle="modal" href="#addcropmodal<%= bed.id %>" role="button">Add Crop</a>
    </div>
    <%# <div class="secondary-card-container"> %>

    <%# ------------- Planted Crop Cards ------------- %>
    <div class="d-flex justify-content-start flex-wrap flex-row">
        <% bed.planted_crops.order(:season).each do |crop| %>
          <%= render "crop", crop: crop %>
        <% end %>
    </div>

    <%# ------------- Unplanted Crop Cards ------------- %>
    <div class="d-flex justify-content-start flex-wrap flex-row">
        <% bed.future_crops.order(:season).each do |crop| %>
          <%= render "crop", crop: crop, bed: bed %>
        <% end %>
    </div>
    <%# </div> %>
    <%# ------------- Modal for adding a crop ------------------ %>
    <div class="modal fade" id="addcropmodal<%= bed.id %>" aria-hidden="true" aria-labelledby="addcropmodal<%= bed.id %>" tabindex="-1">
      <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content rounded-4">
          <div class="modal-header">
            <h2 class="modal-title fs-5" id="addcropmodal<%= bed.id %>"><%= bed.description %> - Add Crop</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="container-fluid">
              <div class="row" data-controller="crop-form">

                <%# ------- Add crop form ------- %>
                <div class="col">
                  <div class="rounded-4 shadow p-3" style="max-width: 30rem;">
                    <%= render "crops/new", bed: bed, crop: @crop %>
                  </div>
                </div>

                <%# -------- Seasonal Recomendation ------- %>
                <div class="col seasonal-container d-flex flex-column justify-content-between">
                  <% @veggie_lists_by_season.each do |list| %>
                    <div class="seasonal-card <%= list.first.season.downcase %> <%= "d-none" unless list.first.season == @season %>"
                        data-crop-form-target="<%= list.first.season.downcase %>">
                      <div class="card shadow rounded-4 mx-2 overflow-hidden border-0" style="max-width: 22rem;">
                        <div class="card-header crop_card_header border-0">
                          <div class="d-flex justify-content-around">
                            <h3 class="season-title text-centre mt-2 mb-0"><%= @seasonal_titles[list.first.season.to_sym] %></h3>
                          </div>
                        </div>
                        <div class="card-body crop_card_body card-bg">
                          <div class="border-0">
                            <div class="rounded-4 card-body card-fg">
                              <div class="copy-bubble rounded-4 m-2 p-3">
                                <em><p class="mb-0">In the month of <%= list.first.season %>, we suggest planting the following:</p></em>
                              </div>
                              <ul>
                                <% list.sort.each do |veggie| %>
                                  <li class="card-text"><i class="fa-regular fa-circle-small"></i><%= veggie.name %></li>
                                <% end %>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>

                  <%# ------- Add a new Veggie -------- %>
                  <div class="add-veggie rounded-4 shadow mt-auto mx-2 p-2">
                    <div class="d-flex flex-row justify-content-between align-items-center my-1">
                      <div>
                        <em><p class="m-0 px-2">Can't find the Veggie you're looking for?</p></em>
                      </div>
                      <button class="btn btn-primary rounded-4" data-bs-target="#addveggiemodal" data-bs-toggle="modal">Add Veggie</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%# ------------- Modal for adding a veggie ------------------ %>
    <div class="modal fade" id="addveggiemodal" aria-hidden="true" aria-labelledby="addveggiemodal" tabindex="-1">
      <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content rounded-4">
          <div class="modal-header">
            <h2 class="modal-title fs-5" id="addveggiemodal">Add Veggie</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="container-fluid">
              <div class="row">
                <%= render "veggies/veggie_form" %>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <%# TODO: fix this back button, may be easier to close instead - worse UI though %>
            <button class="btn btn-warning border" data-bs-target="#addcropmodal<%= bed.id %>" data-bs-toggle="modal"><i class="fa-regular fa-hand-point-left"></i> Back</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gardens/_crop.html.erb
<div class="card border-0 mx-2 my-4 crop-card">
  <div class="card-header crop-card-header">
    <div class="d-flex justify-content-between">
      <%# Name and emoji %>
      <div class="d-flex">
        <h5 class="text-centre mt-2 me-2"><%= crop.emoji %></h5>
        <h5 class="text-centre mt-2"><%= crop.veggie.name %></h5>
      </div>

      <%# Modal exit button %>
      <% if crop.harvested? || current_page?(gardens_path) || current_page?(plans_path)%>
        <button type="button" class="btn-close mt-2" data-bs-dismiss="modal" aria-label="Close"></button>
      <% else %>

        <%# Menu button %>
        <div class="btn-group dropend">
          <button type="button" class="btn btn-light" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-bars" style="font-size: 22px;"></i>
          </button>
          <ul class="dropdown-menu rounded-4 shadow border-0" style="min-width: 130px;">

            <%# Button for editing crop %>
            <li>
              <a class="dropdown-item btn btn-light" data-bs-toggle="modal" href="#editcropmodal<%= crop.id %>"><i class="fa-solid fa-pencil h-60"></i> Edit Crop</a>
            </li>

            <%# Button for deleting crop %>
            <li>
              <%= link_to ('<i class="fa-solid fa-trash-can"></i> Delete Crop').html_safe,
                crop,
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "dropdown-item btn btn-light"
              %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <%# --- Card body --- %>
  <div class="card-body crop-card-body">
    <div class="card border-0 rounded-4">
      <div class="card-body">

        <%# Veggie season badge %>
        <div class="d-flex justify-content-between pb-2 <%= crop.season.downcase %>">
          <span class="badge rounded-4 mb-3"><%= crop.season %></span>
          <% unless current_page?(gardens_path) %>

            <%# Info button %>
            <% if crop.veggie.veggie_tips %>
              <div class="btn-group dropend">
                <button type="button" class="btn btn-light" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa-solid fa-circle-info text-success"></i>
                </button>

                <%# Tips %>
                <ul class="dropdown-menu rounded-4 shadow border-0 tips" style="width: 400px; z-axis:999999;">
                  <div class="tips-text m-3 p-3 rounded-4">
                    <% crop.veggie.veggie_tips.sample(4).each do |tip| %>
                      <li>
                        <p>🐝 <%= tip.tip %></p>
                      </li>
                    <% end %>
                  </div>
                </ul>
              </div>
            <% end %>
          <% end %>
        </div>

        <%# progress bar %>
        <% if crop.planted? %>
          <p class="small text-muted mb-0"><em><%= crop.time_left_to_harvest %></em></p>
          <div class="progress mb-4">
            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="<%= crop.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= crop.progress %>%"></div>
          </div>
        <% else %>
          <div class="mb-3"></div>
        <% end %>
        <% if crop.harvested? %>
          <p class="card-text"><em class="small text-muted">Harvested</em></p>
        <% end %>

        <p class="card-text">Quantity: <em class="text-muted"><%= crop.quantity %></em></p>
        <% if crop.plant_date %>
          <p class="card-text">Date planted: <em class="text-muted"><%= crop.plant_date.to_fs(:long_ordinal) %></em></p>
        <% end %>
        <% if crop.comment.present? %>
          <p class="card-text">Notes: <em class="text-muted"><%= crop.comment %></em></p>
        <% end %>
        <%# button to plant crop %>
        <% unless (crop.planted || crop.plant_date) %>
          <%= link_to 'Plant!', plant_crop_path(crop), class: "btn btn-primary w-100" %>
        <% end %>
        <%# button to harvest crop %>
        <% if crop.planted %>
          <%= link_to 'Harvest!', harvest_crop_path(crop), class: "btn btn-primary w-100" %>
        <% end %>
      </div>
    </div>
  </div>

  <%# ------------- Modal for editing a crop ------------------ %>
  <div class="modal fade" id="editcropmodal<%= crop.id %>" aria-hidden="true" aria-labelledby="editcropmodal<%= crop.id %>" tabindex="-1">
    <div class="modal-dialog modal-xl modal-dialog-centered">
      <div class="modal-content rounded-4">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="editcropmodal<%= crop.id %>"><%= crop.veggie.name %> - Edit Crop</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <div class="row" data-controller="crop-form">
            <%# THIS FORM WILL BE REPLACED - PLEASE DO NOT WORRY TO MUCH ABOUT STYLING %>
              <%= simple_form_for crop do |f| %>
                <div>
                  <%= f.association :veggie, collection: Veggie.all.order(:name), input_html: { class: "rounded-4" } %>
                </div>
                <%= f.input :quantity, input_html: { class: "rounded-4" } %>
                <%= f.input :weeks_to_harvest, input_html: { class: "rounded-4" } %>
                <div class="mb-1">
                  <%= f.label :season %>
                </div>
                <div class="mb-3" data-action="change->crop-form#seasonSelected">
                  <%= f.select :season, %w[Summer Autumn Winter Spring],
                              selected: @season,
                              input_html: { class: "rounded-4" } %>
                </div>
                <div class="mb-1">
                  <%= f.label :emoji %>
                </div>
                <div class="">
                  <%= f.select :emoji, EMOJI_ARRAY, input_html: { class: "rounded-4" } %>
                </div>
                <br>
                <div style="margin: bottom 0;" data-action="change->crop-form#plantedChange">
                  <%= f.input :planted,
                              label: "Has the crop been planted?",
                              as: :radio_buttons,
                              collection: [['Yes', true], ['No', false]],
                              checked: ['No', false],
                              input_html: { class: "rounded-4" } %>
                </div>
                <div class="d-none" data-crop-form-target="date">
                  <%= f.input :plant_date,
                              as: :date,
                              include_blank: true,
                              selected: nil,
                              start_year: Date.today.year - 2,
                              end_year: Date.today.year,
                              input_html: { class: "rounded-4" } %>
                </div>
                <br>
                <%= f.input :comment,
                            label: "Comments",
                            input_html: { class: "rounded-4" } %>
                <div class="d-none">
                  <%= f.association :bed,
                                    label_method: :description,
                                    include_blank: false,
                                    selected: crop.bed.id %>
                </div>
                <div class="btn btn-success rounded-4">
                  <%= f.button :submit, "Save Crop", class: "text-light" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gardens/_form.html.erb
<%=turbo_frame_tag dom_id(garden, :new_garden_form) do %>
  <%= simple_form_for (garden), data: {controller: "turboform"} do |f| %>

      <div class="form-input">
        <%= f.input :name, input_html: { class: "rounded-4" } %>
      </div>
      <div class="form-input">
        <div class="form-actions">
          <div class="col-lg-12 mb-0">
            <div class="d-grid">
              <%= f.button :submit, "Save Garden", class: "btn btn-success text-light"%>
            </div>
          </div>
        </div>
      </div>
  <% end %>
<%end%>

app/views/gardens/_garden.html.erb
<div class="card my-4">
  <div class="card-header garden-header">
    <div class="d-flex justify-content-between">
      <div>
        <%# ------------- Link to Garden Show ------------- %>
        <h2><%= link_to garden.name, garden_path(garden) %></h2>
      </div>

      <!-- ------------------------------- edit garden modal -------------------------------- -->
      <div class="modal fade" id="editgardenmodal<%= garden.id %>" aria-hidden="true" aria-labelledby="editgardenmodal<%= garden.id %>" tabindex="-1">
        <div class="modal-dialog modal-lg modal-dialog-centered">
          <div class="modal-content rounded-4">
            <div class="modal-header">
              <h2 class="modal-title fs-5" id="editgardenmodal<%= garden.id %>">Edit Garden</h2>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div class="container-fluid">
                <div class="row">
                  <!-- ------------------------------- edit garden form -------------------------------- -->
                  <%= render "form", garden: garden %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


      <%# Menu button %>
      <div class="btn-group dropdown">
        <button type="button" class="btn" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-bars" style="font-size: 22px;"></i>
        </button>
        <ul class="dropdown-menu rounded-4 border-0 shadow" style="min-width: 153px;">

          <%# ------------- Icon link to Garden Show ------------- %>
          <li>
            <%= link_to ('<i class="fa-solid fa-binoculars"></i>').html_safe + " View Garden",
                garden_path(garden),
                class: "btn btn-light"
                %>
          </li>

          <%# ------------- Edit Button ------------- %>
          <li>
            <a class="btn btn-light" data-bs-toggle="modal" href="#editgardenmodal<%= garden.id %>" role="button"><i class="fa-solid fa-pencil"></i> Edit Garden</a>
          </li>

          <%# ------------- Delete Garden Button ------------- %>
          <li>
            <%= link_to ('<i class="fa-solid fa-trash-can"></i>').html_safe + " Delete Garden",
                garden,
                data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this garden?" },
                class: "btn btn-light"
                %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="card-body garden current">
    <div class="secondary-card-container">
      <% if garden.beds %>
        <div class="d-flex flex-wrap justify-content-start">
          <%# ------------- Iterate over beds in garden ------------- %>
          <% garden.beds.each do |bed|%>
            <div class="mt-2 mx-4">
              <%# ------------- Bed description badge ------------- %>
              <span class="badge rounded-4 badge-primary ms-1 mb-2"><%= bed.description %></span>
              <div class="card plot-bed mb-2">
                <div class="card-body current-crop-body">
                  <div class="d-flex flex-wrap justify-content-around">
                    <%# ------------- Plot crop emojis in bed (max 12) ------------- %>
                    <% bed.planted_crops.first(12).each do |crop| %>

                      <%# ------------- If 1-2 crops in bed ------------- %>
                      <% if bed.planted_crops.length <= 2 %>
                        <% 6.times do %>
                          <%= render "crops/crop_modal", crop: crop, bed: bed, season: crop.season %>
                        <% end %>

                      <%# ------------- If less that 4 crops in bed ------------- %>
                      <% elsif bed.planted_crops.length <= 4 %>
                        <% 3.times do %>
                          <%= render "crops/crop_modal", crop: crop, bed: bed, season: crop.season %>
                        <% end %>

                      <%# ------------- If 5-6 crops in bed ------------- %>
                      <% elsif bed.planted_crops.length <= 6 %>
                        <% 2.times do %>
                          <%= render "crops/crop_modal", crop: crop, bed: bed, season: crop.season %>
                        <% end %>

                      <%# ------------- If more than 6 crops in bed ------------- %>
                      <% else %>
                        <%= render "crops/crop_modal", crop: crop, bed: bed, season: crop.season %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <%# ------------- No Beds Display ------------- %>
    <% if garden.beds.empty? %>
      <div class="d-flex justify-content-center">
        <div class="card no-plot-bed mt-4" style="padding: 120px 30px;">
          <div class="align-self-center">
            <%= link_to "Get Started", garden_path(garden),
                class: "btn btn-secondary btn-sm btn-pulse-secondary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gardens/_new_garden_form.erb
<%= simple_form_for(garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-input">
      <%= f.input :name %>
    </div>
    <div class="form-input">
      <div class="form-actions">
        <div class="col-lg-12 mb-0">
          <div class="d-grid"> <%= f.button :submit, "Save Garden", class: "btn btn-primary" %></div>
        </div>
      </div>
    </div>
<% end %>

app/views/gardens/_new_garden_form.html.erb
<%=turbo_frame_tag dom_id(garden, :new_garden_form) do %>
  <%= simple_form_for (garden), data: {controller: "turboform"} do |f| %>

      <div class="form-input">
        <%= f.input :name, input_html: { class: "rounded-4" } %>
      </div>
      <div class="form-input">
        <div class="form-actions">
          <div class="col-lg-12 mb-0">
            <div class="d-grid">
              <%= f.button :submit, "Save Garden", class: "btn btn-success text-light"%>
            </div>
          </div>
        </div>
      </div>
  <% end %>
<%end%>

app/views/gardens/index.html.erb
<div class="container main-card-container">
  <!-- ------------------------------- new garden modal -------------------------------- -->
  <div class="modal fade" id="newbedmodal1" aria-hidden="true" aria-labelledby="newbedmodal1" tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered">
      <div class="modal-content rounded-4">
        <div class="modal-header">
          <h2 class="modal-title fs-5" id="newbedmodal1">Add Garden</h2>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <div class="row">
              <!-- ------------------------------- new garden form -------------------------------- -->
              <%= render "form", garden: @garden %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
   <!-- ------------------------------- Title -------------------------------- -->
    <% title = @gardens.length <=1 ? "Garden Overview" : "Gardens Overview" %>
    <div class="align-self-start mb-3"><h1><%= title %></h1></div>

  <!-- ------------------------------- Sub nav -------------------------------- -->
  <div class="d-flex justify-content-between align-items-top">
    <!-- ------------------------------- Info helper -------------------------------- -->
    <%= render "shared/page_info", empty: @gardens.empty? %>
    <!-- ------------------------------- New Garden Button -------------------------------- -->
    <a class="btn btn-primary <%= "btn-pulse-primary" if @gardens.empty? %> align-self-start" style="width:160px;" data-bs-toggle="modal" href="#newbedmodal1" role="button">Add Garden</a>
  </div>
  <%# <div class="main-card-container"> %>
    <% if @gardens %>
    <!-- ------------------------------- Display Garden Cards -------------------------------- -->
      <% @gardens.sort.each do |garden| %>
        <%= render "garden", garden: garden %>
      <% end %>
    <% else %>
      <div class="card my-3">
        <div class="card-header">
          <h2>You don't have any gardens yet</h2>
        </div>
        <div class="card-body no-gardens">
        </div>
      </div>
    <% end %>
  <%# </div> %>
</div>

app/views/gardens/show.html.erb
<div class="container main-card-container">

  <!-- ------------------------------- NEW BED modal1 -------------------------------- -->
  <div class="modal fade" id="newbedmodal1" aria-hidden="true" aria-labelledby="newbedmodal1" tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered">
      <div class="modal-content rounded-4">
        <div class="modal-header">
          <h2 class="modal-title fs-5">Add Bed</h2>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <div class="row">
              <%= render "beds/form", bed: @bed %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- ------------------------------- Title -------------------------------- -->
  <div class="align-self-start mb-3"><h1><%= @garden.name %></h1></div>

  <!-- --------------- sub nav ------------------- -->
  <div class="d-flex justify-content-between align-items-top">
    <!-- ------------------------------- Back to Gardens button -------------------------------- -->
    <%# <%= link_to ('<i class="fa-regular fa-hand-point-left"></i> Back').html_safe,
            gardens_path,
            class: "btn btn-light align-self-start shadow-sm",
            style: "width:120px;"
          %>
  <!-- ------------------------------- Info helper -------------------------------- -->
  <%= render "shared/page_info", empty: @beds.empty? %>
  <!-- ------------------------------- New Bed button -------------------------------- -->
    <a class="btn btn-primary <%= "btn-pulse-primary" if @beds.empty? %> align-self-start" style="width:120px;" data-bs-toggle="modal" href="#newbedmodal1" role="button">Add Bed</a>
  </div>
  <!-- ------------------------------- list all beds in garden -------------------------------- -->
  <%# <div class="main-card-container"> %>
    <% if @beds %>
      <% @beds.reverse.each do |bed| %>
        <%= render "bed", bed: bed %>
      <% end %>
    <% end %>

    <!-- ------------------------------- list all beds in garden -------------------------------- -->
    <% if @beds.empty? %>
      <div class="card my-3">
        <div class="card-header">
          <h2>You don't have any beds yet</h2>
        </div>
        <div class="card-body no-beds">
        </div>
      </div>
    <% end %>
  <%# </div> %>
</div>